# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_merge.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.setEnabled(True)
        Form.resize(532, 440)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK SC Regular")
        font.setPointSize(10)
        Form.setFont(font)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 180, 36))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.removeImageButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.removeImageButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.removeImageButton.setStyleSheet("border:none")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeImageButton.setIcon(icon)
        self.removeImageButton.setObjectName("removeImageButton")
        self.gridLayout.addWidget(self.removeImageButton, 0, 1, 1, 1)
        self.addImageButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.addImageButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addImageButton.setMouseTracking(True)
        self.addImageButton.setStyleSheet("border:none")
        self.addImageButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addImageButton.setIcon(icon1)
        self.addImageButton.setObjectName("addImageButton")
        self.gridLayout.addWidget(self.addImageButton, 0, 0, 1, 1)
        self.downButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.downButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.downButton.setStyleSheet("border:none")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/angle-down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downButton.setIcon(icon2)
        self.downButton.setObjectName("downButton")
        self.gridLayout.addWidget(self.downButton, 0, 4, 1, 1)
        self.startButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.startButton.setEnabled(False)
        self.startButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startButton.setStyleSheet("border:none;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/start.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startButton.setIcon(icon3)
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 0, 5, 1, 1)
        self.resetButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.resetButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetButton.setStyleSheet("border:none")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/redo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetButton.setIcon(icon4)
        self.resetButton.setObjectName("resetButton")
        self.gridLayout.addWidget(self.resetButton, 0, 2, 1, 1)
        self.upButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.upButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.upButton.setStyleSheet("border:none")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/angle-up.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upButton.setIcon(icon5)
        self.upButton.setObjectName("upButton")
        self.gridLayout.addWidget(self.upButton, 0, 3, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 350, 490, 30))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.merge_type_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.merge_type_label.setObjectName("merge_type_label")
        self.gridLayout_4.addWidget(self.merge_type_label, 0, 0, 1, 1)
        self.merge_column_radio = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.merge_column_radio.setObjectName("merge_column_radio")
        self.gridLayout_4.addWidget(self.merge_column_radio, 0, 1, 1, 1)
        self.merge_row_radio = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.merge_row_radio.setObjectName("merge_row_radio")
        self.gridLayout_4.addWidget(self.merge_row_radio, 0, 2, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 390, 490, 36))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.image_save_path_Edit = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_save_path_Edit.sizePolicy().hasHeightForWidth())
        self.image_save_path_Edit.setSizePolicy(sizePolicy)
        self.image_save_path_Edit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.image_save_path_Edit.setReadOnly(True)
        self.image_save_path_Edit.setObjectName("image_save_path_Edit")
        self.gridLayout_5.addWidget(self.image_save_path_Edit, 1, 1, 1, 1)
        self.image_save_path_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.image_save_path_label.setObjectName("image_save_path_label")
        self.gridLayout_5.addWidget(self.image_save_path_label, 1, 0, 1, 1)
        self.image_save_choose = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.image_save_choose.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.image_save_choose.setObjectName("image_save_choose")
        self.gridLayout_5.addWidget(self.image_save_choose, 1, 2, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(20, 60, 490, 280))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 490, 280))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setGeometry(QtCore.QRect(-5, 0, 500, 280))
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget.setObjectName("listWidget")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "图片拼接 v1.4 beta1"))
        self.removeImageButton.setText(_translate("Form", "..."))
        self.downButton.setText(_translate("Form", "..."))
        self.startButton.setText(_translate("Form", "..."))
        self.resetButton.setText(_translate("Form", "..."))
        self.upButton.setText(_translate("Form", "..."))
        self.merge_type_label.setText(_translate("Form", "拼接方式"))
        self.merge_column_radio.setText(_translate("Form", "横向"))
        self.merge_row_radio.setText(_translate("Form", "纵向"))
        self.image_save_path_label.setText(_translate("Form", "保存路径"))
        self.image_save_choose.setText(_translate("Form", "选择"))
